openapi: 3.0.2
info:
  contact:
    url: https://github.com/moov-io/watchman
  description: Moov Watchman offers download, parse, and search functions over numerous
    U.S. trade sanction lists for complying with regional laws. Also included is a
    web UI and async webhook notification service to initiate processes on remote
    systems.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  title: Watchman API
  version: v1
servers:
- description: Local development
  url: http://localhost:8084
tags:
- description: Endpoints for searching individuals and corporations that the U.S.
    government enforces economic sanctions against and adding webhook notifications
    for search criteria.
  name: Watchman
paths:
  /ping:
    get:
      description: Check if the Watchman service is running.
      operationId: ping
      responses:
        "200":
          description: Service is running properly
      summary: Ping Watchman service
      tags:
      - Watchman
  /ofac/companies/{companyID}:
    get:
      description: Get information about a company, trust, or organization such as
        addresses, alternate names, and remarks.
      operationId: getOfacCompany
      parameters:
      - description: Optional Request ID allows application developer to trace requests
          through the system's logs
        explode: false
        in: header
        name: X-Request-ID
        required: false
        schema:
          example: 94c825ee
          type: string
        style: simple
      - description: Company ID
        explode: false
        in: path
        name: companyID
        required: true
        schema:
          example: 1d1c824a
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OfacCompany'
          description: Company and associated metadata
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Error occurred, see response body.
      summary: Get company
      tags:
      - Watchman
    put:
      description: Update a Company's sanction status to always block or always allow
        transactions.
      operationId: updateOfacCompanyStatus
      parameters:
      - description: Optional Request ID allows application developer to trace requests
          through the system's logs
        explode: false
        in: header
        name: X-Request-ID
        required: false
        schema:
          example: 94c825ee
          type: string
        style: simple
      - description: User ID used to perform this search
        explode: false
        in: header
        name: X-User-ID
        required: false
        schema:
          type: string
        style: simple
      - description: Company ID
        explode: false
        in: path
        name: companyID
        required: true
        schema:
          example: 8d49fd61
          type: string
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateOfacCompanyStatus'
        required: true
      responses:
        "200":
          description: Company status updated
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Error occurred, see response body.
      summary: Update company
      tags:
      - Watchman
  /ofac/companies/{companyID}/watch:
    post:
      description: Add ID watch on an OFAC Company.
      operationId: addOfacCompanyWatch
      parameters:
      - description: Optional Request ID allows application developer to trace requests
          through the system's logs
        explode: false
        in: header
        name: X-Request-ID
        required: false
        schema:
          example: 94c825ee
          type: string
        style: simple
      - description: Company ID
        explode: false
        in: path
        name: companyID
        required: true
        schema:
          example: c3cf0f66
          type: string
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/OfacWatchRequest'
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OfacWatch'
          description: Company watch added
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Error occurred, see response body.
        "404":
          description: Company not found
      summary: Watch OFAC company
      tags:
      - Watchman
  /ofac/companies/{companyID}/watch/{watchID}:
    delete:
      description: Delete a company ID watch.
      operationId: removeOfacCompanyWatch
      parameters:
      - description: Optional Request ID allows application developer to trace requests
          through the system's logs
        explode: false
        in: header
        name: X-Request-ID
        required: false
        schema:
          example: 94c825ee
          type: string
        style: simple
      - description: Company ID
        explode: false
        in: path
        name: companyID
        required: true
        schema:
          example: c3cf0f66
          type: string
        style: simple
      - description: Watch ID, used to identify a specific watch
        explode: false
        in: path
        name: watchID
        required: true
        schema:
          example: 0c5e215c
          type: string
        style: simple
      responses:
        "200":
          description: Company watch removed
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Error occurred, see response body.
      summary: Remove company watch
      tags:
      - Watchman
  /ofac/companies/watch:
    post:
      description: Watch a company by its name. The match percentage will be included
        in the webhook's JSON payload.
      operationId: addOfacCompanyNameWatch
      parameters:
      - description: Optional Request ID allows application developer to trace requests
          through the system's logs
        explode: false
        in: header
        name: X-Request-ID
        required: false
        schema:
          example: 94c825ee
          type: string
        style: simple
      - description: Company name used to match and send watch notifications
        explode: true
        in: query
        name: name
        required: true
        schema:
          example: Jane Smith
          type: string
        style: form
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/OfacWatchRequest'
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OfacWatch'
          description: Company watch applied
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Error occurred, see response body.
      summary: Watch company
      tags:
      - Watchman
  /ofac/companies/watch/{watchID}:
    delete:
      description: Delete a company name watch.
      operationId: removeOfacCompanyNameWatch
      parameters:
      - description: Optional Request ID allows application developer to trace requests
          through the system's logs
        explode: false
        in: header
        name: X-Request-ID
        required: false
        schema:
          example: 94c825ee
          type: string
        style: simple
      - description: Watch ID, used to identify a specific watch
        explode: false
        in: path
        name: watchID
        required: true
        schema:
          example: 0c5e215c
          type: string
        style: simple
      - description: Company name watch
        explode: true
        in: query
        name: name
        required: true
        schema:
          example: Jane Smith
          type: string
        style: form
      responses:
        "200":
          description: Company watch removed
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Error occurred, see response body.
      summary: Remove company watch
      tags:
      - Watchman
  /ofac/customers/{customerID}:
    get:
      description: Get information about a customer's addresses, alternate names,
        and SDN metadata.
      operationId: getOfacCustomer
      parameters:
      - description: Optional Request ID allows application developer to trace requests
          through the system's logs
        explode: false
        in: header
        name: X-Request-ID
        required: false
        schema:
          example: 94c825ee
          type: string
        style: simple
      - description: Customer ID
        explode: false
        in: path
        name: customerID
        required: true
        schema:
          example: c3cf0f66
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OfacCustomer'
          description: Customer and associated metadata
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Error occurred, see response body.
      summary: Get customer
      tags:
      - Watchman
    put:
      description: Update a Customer sanction status to always block or always allow
        transactions.
      operationId: updateOfacCustomerStatus
      parameters:
      - description: Optional Request ID allows application developer to trace requests
          through the system's logs
        explode: false
        in: header
        name: X-Request-ID
        required: false
        schema:
          example: 94c825ee
          type: string
        style: simple
      - description: User ID used to perform this search
        explode: false
        in: header
        name: X-User-ID
        required: false
        schema:
          type: string
        style: simple
      - description: Customer ID
        explode: false
        in: path
        name: customerID
        required: true
        schema:
          example: c3cf0f66
          type: string
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateOfacCustomerStatus'
        required: true
      responses:
        "200":
          description: Customer status updated
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Error occurred, see response body.
      summary: Update customer
      tags:
      - Watchman
  /ofac/customers/{customerID}/watch:
    post:
      description: Add ID watch on an OFAC Customer.
      operationId: addOfacCustomerWatch
      parameters:
      - description: Optional Request ID allows application developer to trace requests
          through the system's logs
        explode: false
        in: header
        name: X-Request-ID
        required: false
        schema:
          example: 94c825ee
          type: string
        style: simple
      - description: Customer ID
        explode: false
        in: path
        name: customerID
        required: true
        schema:
          example: c3cf0f66
          type: string
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/OfacWatchRequest'
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OfacWatch'
          description: Customer watch added
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Error occurred, see response body.
        "404":
          description: Customer not found
      summary: Watch OFAC customer
      tags:
      - Watchman
  /ofac/customers/{customerID}/watch/{watchID}:
    delete:
      description: Delete a customer ID watch.
      operationId: removeOfacCustomerWatch
      parameters:
      - description: Optional Request ID allows application developer to trace requests
          through the system's logs
        explode: false
        in: header
        name: X-Request-ID
        required: false
        schema:
          example: 94c825ee
          type: string
        style: simple
      - description: Customer ID
        explode: false
        in: path
        name: customerID
        required: true
        schema:
          example: c3cf0f66
          type: string
        style: simple
      - description: Watch ID, used to identify a specific watch
        explode: false
        in: path
        name: watchID
        required: true
        schema:
          example: 0c5e215c
          type: string
        style: simple
      responses:
        "200":
          description: Customer watch removed
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Error occurred, see response body.
      summary: Remove customer watch
      tags:
      - Watchman
  /ofac/customers/watch:
    post:
      description: Watch a customer by its name. The match percentage will be included
        in the webhook's JSON payload.
      operationId: addOfacCustomerNameWatch
      parameters:
      - description: Optional Request ID allows application developer to trace requests
          through the system's logs
        explode: false
        in: header
        name: X-Request-ID
        required: false
        schema:
          example: 94c825ee
          type: string
        style: simple
      - description: Individual name used to match and send watch notifications
        explode: true
        in: query
        name: name
        required: true
        schema:
          example: Jane Smith
          type: string
        style: form
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/OfacWatchRequest'
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OfacWatch'
          description: Customer watch applied
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Error occurred, see response body.
      summary: Watch customer
      tags:
      - Watchman
  /ofac/customers/watch/{watchID}:
    delete:
      description: Delete a customer name watch.
      operationId: removeOfacCustomerNameWatch
      parameters:
      - description: Optional Request ID allows application developer to trace requests
          through the system's logs
        explode: false
        in: header
        name: X-Request-ID
        required: false
        schema:
          example: 94c825ee
          type: string
        style: simple
      - description: Watch ID, used to identify a specific watch
        explode: false
        in: path
        name: watchID
        required: true
        schema:
          example: 0c5e215c
          type: string
        style: simple
      - description: Customer or Company name watch
        explode: true
        in: query
        name: name
        required: true
        schema:
          example: Jane Smith
          type: string
        style: form
      responses:
        "200":
          description: Company or Customer watch removed
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Error occurred, see response body.
      summary: Remove customer watch
      tags:
      - Watchman
  /ofac/sdn/{sdnID}:
    get:
      description: Get SDN details
      operationId: getSDN
      parameters:
      - description: Optional Request ID allows application developer to trace requests
          through the system's logs
        explode: false
        in: header
        name: X-Request-ID
        required: false
        schema:
          example: 94c825ee
          type: string
        style: simple
      - description: SDN ID
        explode: false
        in: path
        name: sdnID
        required: true
        schema:
          example: 564dd7d1
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OfacSDN'
          description: SDN metadata
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Error occurred, see response body.
      summary: Get SDN
      tags:
      - Watchman
  /ofac/sdn/{sdnID}/alts:
    get:
      operationId: getSDNAltNames
      parameters:
      - description: Optional Request ID allows application developer to trace requests
          through the system's logs
        explode: false
        in: header
        name: X-Request-ID
        required: false
        schema:
          example: 94c825ee
          type: string
        style: simple
      - description: SDN ID
        explode: false
        in: path
        name: sdnID
        required: true
        schema:
          example: 564dd7d1
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OfacSDNAltNames'
          description: SDN alternate names
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Error occurred, see response body.
      summary: Get SDN alt names
      tags:
      - Watchman
  /ofac/sdn/{sdnID}/addresses:
    get:
      operationId: getSDNAddresses
      parameters:
      - description: Optional Request ID allows application developer to trace requests
          through the system's logs
        explode: false
        in: header
        name: X-Request-ID
        required: false
        schema:
          example: 94c825ee
          type: string
        style: simple
      - description: SDN ID
        explode: false
        in: path
        name: sdnID
        required: true
        schema:
          example: 564dd7d1
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OfacEntityAddresses'
          description: SDN addresses
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Error occurred, see response body.
      summary: Get SDN addresses
      tags:
      - Watchman
  /search:
    get:
      operationId: search
      parameters:
      - description: Optional Request ID allows application developer to trace requests
          through the system's logs
        explode: false
        in: header
        name: X-Request-ID
        required: false
        schema:
          example: 94c825ee
          type: string
        style: simple
      - description: Search across Name, Alt Names, and SDN Address fields for all
          available sanctions lists. Entries may be returned in all response sub-objects.
        explode: true
        in: query
        name: q
        required: false
        schema:
          example: John Doe
          type: string
        style: form
      - description: Name which could correspond to an entry on the SDN, Denied Persons,
          Sectoral Sanctions Identifications, or BIS Entity List sanctions lists.
          Alt names are also searched.
        explode: true
        in: query
        name: name
        required: false
        schema:
          example: Jane Smith
          type: string
        style: form
      - description: Physical address which could correspond to a human on the SDN
          list. Only Address results will be returned.
        explode: true
        in: query
        name: address
        required: false
        schema:
          example: 123 83rd Ave
          type: string
        style: form
      - description: City name as desginated by SDN guidelines. Only Address results
          will be returned.
        explode: true
        in: query
        name: city
        required: false
        schema:
          example: USA
          type: string
        style: form
      - description: State name as desginated by SDN guidelines. Only Address results
          will be returned.
        explode: true
        in: query
        name: state
        required: false
        schema:
          example: USA
          type: string
        style: form
      - description: Providence name as desginated by SDN guidelines. Only Address
          results will be returned.
        explode: true
        in: query
        name: providence
        required: false
        schema:
          example: USA
          type: string
        style: form
      - description: Zip code as desginated by SDN guidelines. Only Address results
          will be returned.
        explode: true
        in: query
        name: zip
        required: false
        schema:
          example: USA
          type: string
        style: form
      - description: Country name as desginated by SDN guidelines. Only Address results
          will be returned.
        explode: true
        in: query
        name: country
        required: false
        schema:
          example: USA
          type: string
        style: form
      - description: Alternate name which could correspond to a human on the SDN list.
          Only Alt name results will be returned.
        explode: true
        in: query
        name: altName
        required: false
        schema:
          example: Jane Smith
          type: string
        style: form
      - description: ID value often found in remarks property of an SDN. Takes the
          form of 'No. NNNNN' as an alphanumeric value.
        explode: true
        in: query
        name: id
        required: false
        schema:
          example: "10517860"
          type: string
        style: form
      - description: Match percentage that search query must obtain for results to
          be returned.
        explode: true
        in: query
        name: minMatch
        required: false
        schema:
          example: 0.95
          format: float
          type: number
        style: form
      - description: Maximum results returned by a search. Results are sorted by their
          match percentage in decending order.
        explode: true
        in: query
        name: limit
        required: false
        schema:
          example: 25
          type: integer
        style: form
      - description: Optional filter to only return SDNs whose type case-insensitively
          matches.
        explode: true
        in: query
        name: sdnType
        required: false
        schema:
          example: individual
          type: string
        style: form
      - description: Optional filter to only return SDNs whose program case-insensitively
          matches.
        explode: true
        in: query
        name: program
        required: false
        schema:
          example: SDGT
          type: string
        style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Search'
          description: SDNs returned from a search
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Error occurred, see response body.
      summary: Search SDNs
      tags:
      - Watchman
  /downloads:
    get:
      description: Return list of recent downloads of list data.
      operationId: getLatestDownloads
      parameters:
      - description: Optional Request ID allows application developer to trace requests
          through the system's logs
        explode: false
        in: header
        name: X-Request-ID
        required: false
        schema:
          example: 94c825ee
          type: string
        style: simple
      - description: Maximum number of downloads to return sorted by their timestamp
          in decending order.
        explode: true
        in: query
        name: limit
        required: false
        schema:
          example: 25
          type: integer
        style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Downloads'
          description: Recent timestamps and counts of parsed objects
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Error occurred, see response body.
      summary: Get latest downloads
      tags:
      - Watchman
  /ui/values/{key}:
    get:
      description: Return an ordered distinct list of keys for an SDN property.
      operationId: getUIValues
      parameters:
      - description: SDN property to lookup. Values are sdnType, ofacProgram
        explode: false
        in: path
        name: key
        required: true
        schema:
          example: sdnType
          type: string
        style: simple
      - description: Maximum number of UI keys returned
        explode: true
        in: query
        name: limit
        required: false
        schema:
          example: 25
          type: integer
        style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UIKeys'
          description: Ordered and distinct list of values for an SDN property
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Error occurred, see response body.
      summary: Get UI values
      tags:
      - Watchman
components:
  schemas:
    OfacCompany:
      description: OFAC Company and metadata
      example:
        addresses:
        - country: Japan
          address: 123 73th St
          cityStateProvincePostalCode: Tokyo 103
          match: 0.91
          entityID: "2112"
          addressID: "201"
        - country: Japan
          address: 123 73th St
          cityStateProvincePostalCode: Tokyo 103
          match: 0.91
          entityID: "2112"
          addressID: "201"
        alts:
        - alternateID: "220"
          alternateRemarks: Extra information
          alternateType: aka
          match: 0.91
          entityID: "306"
          alternateName: NATIONAL BANK OF CUBA
        - alternateID: "220"
          alternateRemarks: Extra information
          alternateType: aka
          match: 0.91
          entityID: "306"
          alternateName: NATIONAL BANK OF CUBA
        ID: 9574756b
        sdn:
          match: 0.91
          entityID: "1231"
          programs:
          - CUBA
          sdnName: BANCO NACIONAL DE CUBA
          title: Title of an individual
          remarks: Additional info
        status:
          note: Incorrect match
          createdAt: 2000-01-23T04:56:07.000+00:00
          userID: 349661f9
          status: unsafe
      properties:
        ID:
          description: OFAC Company ID
          example: 9574756b
          type: string
        sdn:
          $ref: '#/components/schemas/OfacSDN'
        addresses:
          items:
            $ref: '#/components/schemas/OfacEntityAddress'
          type: array
        alts:
          items:
            $ref: '#/components/schemas/OfacAlt'
          type: array
        status:
          $ref: '#/components/schemas/OfacCompanyStatus'
    OfacCompanyStatus:
      description: Status properties of an OFAC Company
      example:
        note: Incorrect match
        createdAt: 2000-01-23T04:56:07.000+00:00
        userID: 349661f9
        status: unsafe
      properties:
        userID:
          description: User ID provided when updating status
          example: 349661f9
          type: string
        note:
          description: Optional note from updating status
          example: Incorrect match
          type: string
        status:
          description: Manually applied status for OFAC Company
          enum:
          - unsafe
          - exception
          type: string
        createdAt:
          format: date-time
          type: string
    OfacCustomer:
      description: OFAC Customer and metadata
      example:
        addresses:
        - country: Japan
          address: 123 73th St
          cityStateProvincePostalCode: Tokyo 103
          match: 0.91
          entityID: "2112"
          addressID: "201"
        - country: Japan
          address: 123 73th St
          cityStateProvincePostalCode: Tokyo 103
          match: 0.91
          entityID: "2112"
          addressID: "201"
        alts:
        - alternateID: "220"
          alternateRemarks: Extra information
          alternateType: aka
          match: 0.91
          entityID: "306"
          alternateName: NATIONAL BANK OF CUBA
        - alternateID: "220"
          alternateRemarks: Extra information
          alternateType: aka
          match: 0.91
          entityID: "306"
          alternateName: NATIONAL BANK OF CUBA
        ID: 9574756b
        sdn:
          match: 0.91
          entityID: "1231"
          programs:
          - CUBA
          sdnName: BANCO NACIONAL DE CUBA
          title: Title of an individual
          remarks: Additional info
        status:
          note: Incorrect match
          createdAt: 2000-01-23T04:56:07.000+00:00
          userID: 349661f9
          status: unsafe
      properties:
        ID:
          description: OFAC Customer ID
          example: 9574756b
          type: string
        sdn:
          $ref: '#/components/schemas/OfacSDN'
        addresses:
          items:
            $ref: '#/components/schemas/OfacEntityAddress'
          type: array
        alts:
          items:
            $ref: '#/components/schemas/OfacAlt'
          type: array
        status:
          $ref: '#/components/schemas/OfacCustomerStatus'
    OfacCustomerStatus:
      description: Status properties of an OFAC Customer
      example:
        note: Incorrect match
        createdAt: 2000-01-23T04:56:07.000+00:00
        userID: 349661f9
        status: unsafe
      properties:
        userID:
          description: User ID provided when updating status
          example: 349661f9
          type: string
        note:
          description: Optional note from updating status
          example: Incorrect match
          type: string
        status:
          description: Manually applied status for OFAC Customer
          enum:
          - unsafe
          - exception
          type: string
        createdAt:
          format: date-time
          type: string
    OfacSDN:
      description: Specially designated national from OFAC list
      example:
        match: 0.91
        entityID: "1231"
        programs:
        - CUBA
        sdnName: BANCO NACIONAL DE CUBA
        title: Title of an individual
        remarks: Additional info
      properties:
        entityID:
          example: "1231"
          type: string
        sdnName:
          example: BANCO NACIONAL DE CUBA
          type: string
        sdnType:
          $ref: '#/components/schemas/SdnType'
        programs:
          description: Programs is the sanction programs this SDN was added from
          example:
          - CUBA
          items:
            type: string
          type: array
        title:
          example: Title of an individual
          type: string
        remarks:
          description: Remarks on SDN and often additional information about the SDN
          example: Additional info
          type: string
        match:
          description: Match percentage of search query
          example: 0.91
          type: number
    OfacEntityAddresses:
      items:
        $ref: '#/components/schemas/OfacEntityAddress'
      type: array
    OfacEntityAddress:
      description: Physical address from OFAC list
      example:
        country: Japan
        address: 123 73th St
        cityStateProvincePostalCode: Tokyo 103
        match: 0.91
        entityID: "2112"
        addressID: "201"
      properties:
        entityID:
          example: "2112"
          type: string
        addressID:
          example: "201"
          type: string
        address:
          example: 123 73th St
          type: string
        cityStateProvincePostalCode:
          example: Tokyo 103
          type: string
        country:
          example: Japan
          type: string
        match:
          description: Match percentage of search query
          example: 0.91
          type: number
    OfacSDNAltNames:
      items:
        $ref: '#/components/schemas/OfacAlt'
      type: array
    OfacAlt:
      description: Alternate name from OFAC list
      example:
        alternateID: "220"
        alternateRemarks: Extra information
        alternateType: aka
        match: 0.91
        entityID: "306"
        alternateName: NATIONAL BANK OF CUBA
      properties:
        entityID:
          example: "306"
          type: string
        alternateID:
          example: "220"
          type: string
        alternateType:
          example: aka
          type: string
        alternateName:
          example: NATIONAL BANK OF CUBA
          type: string
        alternateRemarks:
          example: Extra information
          type: string
        match:
          description: Match percentage of search query
          example: 0.91
          type: number
    SdnType:
      description: Used for classifying SDNs — typically represents an individual
        or company
      enum:
      - individual
      - entity
      - vessel
      - aircraft
      type: string
    SsiType:
      description: Used for classifying SSIs
      enum:
      - individual
      - entity
      type: string
    DPL:
      description: BIS Denied Persons List item
      example:
        country: United States
        city: THREE RIVERS
        postalCode: "78071"
        match: 0.92
        standardOrder: "Y"
        frCitation: 81.F.R. 40658 6/22/2016
        streetAddress: 'REGISTER NUMBER: 78795-379, FEDERAL CORRECTIONAL INSTITUTION,
          P.O. BOX 4200'
        lastUpdate: 2016-06-22
        name: ISMAEL RETA
        action: FR NOTICE ADDED
        state: TX
        effectiveDate: 06/15/2016
        expirationDate: 06/15/2025
      properties:
        name:
          description: Denied Person's name
          example: ISMAEL RETA
          type: string
        streetAddress:
          description: Denied Person's street address
          example: 'REGISTER NUMBER: 78795-379, FEDERAL CORRECTIONAL INSTITUTION,
            P.O. BOX 4200'
          type: string
        city:
          description: Denied Person's city
          example: THREE RIVERS
          type: string
        state:
          description: Denied Person's state
          example: TX
          type: string
        country:
          description: Denied Person's country
          example: United States
          type: string
        postalCode:
          description: Denied Person's postal code
          example: "78071"
          type: string
        effectiveDate:
          description: Date when denial came into effect
          example: 06/15/2016
          type: string
        expirationDate:
          description: Date when denial expires, if blank denial never expires
          example: 06/15/2025
          type: string
        standardOrder:
          description: Denotes whether or not the Denied Person was added by a standard
            order
          example: "Y"
          type: string
        lastUpdate:
          description: Date when the Denied Person's record was most recently updated
          example: 2016-06-22
          type: string
        action:
          description: Most recent action taken regarding the denial
          example: FR NOTICE ADDED
          type: string
        frCitation:
          description: Reference to the order's citation in the Federal Register
          example: 81.F.R. 40658 6/22/2016
          type: string
        match:
          description: Match percentage of search query
          example: 0.92
          type: number
    SSI:
      description: Treasury Department Sectoral Sanctions Identifications List (SSI)
      example:
        sourceInfoURL: http://bit.ly/1MLgou0
        addresses:
        - D. Retyum, Luzhski Raion, Leningradskaya Obl., 188230, RU
        - Retiun Village, Lujskiy District, Leningrad Region, RU
        alternateNames:
        - VERKHNECHONSKNEFTEGAZ
        - OJSC VERKHNECHONSKNEFTEGAZ
        name: PJSC VERKHNECHONSKNEFTEGAZ
        ids:
        - Subject to Directive 4, Executive Order 13662 Directive Determination
        - vcng@rosneft.ru, Email Address
        - Subject to Directive 2, Executive Order 13662 Directive Determination
        entityID: "1231"
        programs:
        - UKRAINE-EO13662
        - SYRIA
        sourceListURL: http://bit.ly/1MLgou0
        remarks:
        - 'For more information on directives, please visit the following link: http://www.treasury.gov/resource-center/sanctions/Programs/Pages/ukraine.aspx#directives.'
        - '(Linked To: OPEN JOINT-STOCK COMPANY ROSNEFT OIL COMPANY)'
      properties:
        entityID:
          description: The ID assigned to an entity by the Treasury Department
          example: "1231"
          type: string
        type:
          $ref: '#/components/schemas/SsiType'
        programs:
          description: Sanction programs for which the entity is flagged
          example:
          - UKRAINE-EO13662
          - SYRIA
          items:
            type: string
          type: array
        name:
          description: The name of the entity
          example: PJSC VERKHNECHONSKNEFTEGAZ
          type: string
        addresses:
          description: Addresses associated with the entity
          example:
          - D. Retyum, Luzhski Raion, Leningradskaya Obl., 188230, RU
          - Retiun Village, Lujskiy District, Leningrad Region, RU
          items:
            type: string
          type: array
        remarks:
          description: Additional details regarding the entity
          example:
          - 'For more information on directives, please visit the following link:
            http://www.treasury.gov/resource-center/sanctions/Programs/Pages/ukraine.aspx#directives.'
          - '(Linked To: OPEN JOINT-STOCK COMPANY ROSNEFT OIL COMPANY)'
          items:
            type: string
          type: array
        alternateNames:
          description: Known aliases associated with the entity
          example:
          - VERKHNECHONSKNEFTEGAZ
          - OJSC VERKHNECHONSKNEFTEGAZ
          items:
            type: string
          type: array
        ids:
          description: IDs on file for the entity
          example:
          - Subject to Directive 4, Executive Order 13662 Directive Determination
          - vcng@rosneft.ru, Email Address
          - Subject to Directive 2, Executive Order 13662 Directive Determination
          items:
            type: string
          type: array
        sourceListURL:
          description: The link to the official SSI list
          example: http://bit.ly/1MLgou0
          type: string
        sourceInfoURL:
          description: The link for information regarding the source
          example: http://bit.ly/1MLgou0
          type: string
    BISEntities:
      description: Bureau of Industry and Security Entity List
      example:
        licenseRequirement: For all items subject to the EAR. (See ¬ß744.11 of the
          EAR).
        sourceInfoURL: http://bit.ly/1MLgou0
        addresses:
        - D. Retyum, Luzhski Raion, Leningradskaya Obl., 188230, RU
        - Retiun Village, Lujskiy District, Leningrad Region, RU
        alternateNames:
        - VERKHNECHONSKNEFTEGAZ
        - OJSC VERKHNECHONSKNEFTEGAZ
        licensePolicy: Presumption of denial.
        name: Luhansk People¬ís Republic
        sourceListURL: http://bit.ly/1MLgou0
        startDate: 6/21/16
        frNotice: 81 FR 61595
      properties:
        name:
          description: The name of the entity
          example: Luhansk People¬ís Republic
          type: string
        addresses:
          description: Addresses associated with the entity
          example:
          - D. Retyum, Luzhski Raion, Leningradskaya Obl., 188230, RU
          - Retiun Village, Lujskiy District, Leningrad Region, RU
          items:
            type: string
          type: array
        alternateNames:
          description: Known aliases associated with the entity
          example:
          - VERKHNECHONSKNEFTEGAZ
          - OJSC VERKHNECHONSKNEFTEGAZ
          items:
            type: string
          type: array
        startDate:
          description: Date when the restriction came into effect
          example: 6/21/16
          type: string
        licenseRequirement:
          description: Specifies the license requirement imposed on the named entity
          example: For all items subject to the EAR. (See ¬ß744.11 of the EAR).
          type: string
        licensePolicy:
          description: Identifies the policy BIS uses to review the licenseRequirements
          example: Presumption of denial.
          type: string
        frNotice:
          description: Identifies the corresponding Notice in the Federal Register
          example: 81 FR 61595
          type: string
        sourceListURL:
          description: The link to the official SSI list
          example: http://bit.ly/1MLgou0
          type: string
        sourceInfoURL:
          description: The link for information regarding the source
          example: http://bit.ly/1MLgou0
          type: string
    UpdateOfacCompanyStatus:
      description: Request body to update a company status.
      example:
        notes: False positive
        status: unsafe
      properties:
        status:
          description: Manual override of company/SDN sanction status
          enum:
          - unsafe
          - exception
          type: string
        notes:
          description: Free form notes about manually changing the Company status
          example: False positive
          type: string
      required:
      - status
    UpdateOfacCustomerStatus:
      description: Request body to update a customers status.
      example:
        notes: False positive
        status: unsafe
      properties:
        status:
          description: Manual override of customer/SDN sanction status
          enum:
          - unsafe
          - exception
          type: string
        notes:
          description: Free form notes about manually changing the Customer status
          example: False positive
          type: string
      required:
      - status
    Search:
      description: Search results containing SDNs, alternate names, and/or addreses
      example:
        SDNs:
        - match: 0.91
          entityID: "1231"
          programs:
          - CUBA
          sdnName: BANCO NACIONAL DE CUBA
          title: Title of an individual
          remarks: Additional info
        - match: 0.91
          entityID: "1231"
          programs:
          - CUBA
          sdnName: BANCO NACIONAL DE CUBA
          title: Title of an individual
          remarks: Additional info
        altNames:
        - alternateID: "220"
          alternateRemarks: Extra information
          alternateType: aka
          match: 0.91
          entityID: "306"
          alternateName: NATIONAL BANK OF CUBA
        - alternateID: "220"
          alternateRemarks: Extra information
          alternateType: aka
          match: 0.91
          entityID: "306"
          alternateName: NATIONAL BANK OF CUBA
        addresses:
        - country: Japan
          address: 123 73th St
          cityStateProvincePostalCode: Tokyo 103
          match: 0.91
          entityID: "2112"
          addressID: "201"
        - country: Japan
          address: 123 73th St
          cityStateProvincePostalCode: Tokyo 103
          match: 0.91
          entityID: "2112"
          addressID: "201"
        deniedPersons:
        - country: United States
          city: THREE RIVERS
          postalCode: "78071"
          match: 0.92
          standardOrder: "Y"
          frCitation: 81.F.R. 40658 6/22/2016
          streetAddress: 'REGISTER NUMBER: 78795-379, FEDERAL CORRECTIONAL INSTITUTION,
            P.O. BOX 4200'
          lastUpdate: 2016-06-22
          name: ISMAEL RETA
          action: FR NOTICE ADDED
          state: TX
          effectiveDate: 06/15/2016
          expirationDate: 06/15/2025
        - country: United States
          city: THREE RIVERS
          postalCode: "78071"
          match: 0.92
          standardOrder: "Y"
          frCitation: 81.F.R. 40658 6/22/2016
          streetAddress: 'REGISTER NUMBER: 78795-379, FEDERAL CORRECTIONAL INSTITUTION,
            P.O. BOX 4200'
          lastUpdate: 2016-06-22
          name: ISMAEL RETA
          action: FR NOTICE ADDED
          state: TX
          effectiveDate: 06/15/2016
          expirationDate: 06/15/2025
        bisEntities:
        - licenseRequirement: For all items subject to the EAR. (See ¬ß744.11 of the
            EAR).
          sourceInfoURL: http://bit.ly/1MLgou0
          addresses:
          - D. Retyum, Luzhski Raion, Leningradskaya Obl., 188230, RU
          - Retiun Village, Lujskiy District, Leningrad Region, RU
          alternateNames:
          - VERKHNECHONSKNEFTEGAZ
          - OJSC VERKHNECHONSKNEFTEGAZ
          licensePolicy: Presumption of denial.
          name: Luhansk People¬ís Republic
          sourceListURL: http://bit.ly/1MLgou0
          startDate: 6/21/16
          frNotice: 81 FR 61595
        - licenseRequirement: For all items subject to the EAR. (See ¬ß744.11 of the
            EAR).
          sourceInfoURL: http://bit.ly/1MLgou0
          addresses:
          - D. Retyum, Luzhski Raion, Leningradskaya Obl., 188230, RU
          - Retiun Village, Lujskiy District, Leningrad Region, RU
          alternateNames:
          - VERKHNECHONSKNEFTEGAZ
          - OJSC VERKHNECHONSKNEFTEGAZ
          licensePolicy: Presumption of denial.
          name: Luhansk People¬ís Republic
          sourceListURL: http://bit.ly/1MLgou0
          startDate: 6/21/16
          frNotice: 81 FR 61595
        refreshedAt: 2000-01-23T04:56:07.000+00:00
        sectoralSanctions:
        - sourceInfoURL: http://bit.ly/1MLgou0
          addresses:
          - D. Retyum, Luzhski Raion, Leningradskaya Obl., 188230, RU
          - Retiun Village, Lujskiy District, Leningrad Region, RU
          alternateNames:
          - VERKHNECHONSKNEFTEGAZ
          - OJSC VERKHNECHONSKNEFTEGAZ
          name: PJSC VERKHNECHONSKNEFTEGAZ
          ids:
          - Subject to Directive 4, Executive Order 13662 Directive Determination
          - vcng@rosneft.ru, Email Address
          - Subject to Directive 2, Executive Order 13662 Directive Determination
          entityID: "1231"
          programs:
          - UKRAINE-EO13662
          - SYRIA
          sourceListURL: http://bit.ly/1MLgou0
          remarks:
          - 'For more information on directives, please visit the following link:
            http://www.treasury.gov/resource-center/sanctions/Programs/Pages/ukraine.aspx#directives.'
          - '(Linked To: OPEN JOINT-STOCK COMPANY ROSNEFT OIL COMPANY)'
        - sourceInfoURL: http://bit.ly/1MLgou0
          addresses:
          - D. Retyum, Luzhski Raion, Leningradskaya Obl., 188230, RU
          - Retiun Village, Lujskiy District, Leningrad Region, RU
          alternateNames:
          - VERKHNECHONSKNEFTEGAZ
          - OJSC VERKHNECHONSKNEFTEGAZ
          name: PJSC VERKHNECHONSKNEFTEGAZ
          ids:
          - Subject to Directive 4, Executive Order 13662 Directive Determination
          - vcng@rosneft.ru, Email Address
          - Subject to Directive 2, Executive Order 13662 Directive Determination
          entityID: "1231"
          programs:
          - UKRAINE-EO13662
          - SYRIA
          sourceListURL: http://bit.ly/1MLgou0
          remarks:
          - 'For more information on directives, please visit the following link:
            http://www.treasury.gov/resource-center/sanctions/Programs/Pages/ukraine.aspx#directives.'
          - '(Linked To: OPEN JOINT-STOCK COMPANY ROSNEFT OIL COMPANY)'
      properties:
        SDNs:
          items:
            $ref: '#/components/schemas/OfacSDN'
          type: array
        altNames:
          items:
            $ref: '#/components/schemas/OfacAlt'
          type: array
        addresses:
          items:
            $ref: '#/components/schemas/OfacEntityAddress'
          type: array
        sectoralSanctions:
          items:
            $ref: '#/components/schemas/SSI'
          type: array
        deniedPersons:
          items:
            $ref: '#/components/schemas/DPL'
          type: array
        bisEntities:
          items:
            $ref: '#/components/schemas/BISEntities'
          type: array
        refreshedAt:
          format: date-time
          type: string
    OfacWatch:
      description: Customer or Company watch
      example:
        watchID: 08ddba92
      properties:
        watchID:
          description: Object representing a customer or company watch
          example: 08ddba92
          type: string
    OfacWatchRequest:
      description: Webhook or other means of notification on search criteria. OFAC
        will make a POST request with a body of the customer or company (SDN, AltNames,
        and Address).
      example:
        webhook: https://api.example.com/ofac/webhook
        authToken: 75d0384b-a105-4048-9fce-91a280ce7337
      properties:
        authToken:
          description: Private token supplied by clients to be used for authenticating
            webhooks.
          example: 75d0384b-a105-4048-9fce-91a280ce7337
          type: string
        webhook:
          description: HTTPS url for webhook on search match
          example: https://api.example.com/ofac/webhook
          type: string
      required:
      - authToken
      - webhook
    Downloads:
      items:
        $ref: '#/components/schemas/Download'
      type: array
    Download:
      description: Metadata and stats about downloaded OFAC data
      example:
        SDNs: 7414
        altNames: 9729
        addresses: 11747
        deniedPersons: 842
        bisEntities: 1391
        sectoralSanctions: 329
        timestamp: 2000-01-23T04:56:07.000+00:00
      properties:
        SDNs:
          example: 7414
          type: integer
        altNames:
          example: 9729
          type: integer
        addresses:
          example: 11747
          type: integer
        sectoralSanctions:
          example: 329
          type: integer
        deniedPersons:
          example: 842
          type: integer
        bisEntities:
          example: 1391
          type: integer
        timestamp:
          format: date-time
          type: string
    UIKeys:
      items:
        $ref: '#/components/schemas/SdnType'
      type: array
      uniqueItems: true
    Error:
      properties:
        error:
          description: An error message describing the problem intended for humans.
          example: Example error, see description
          type: string
      required:
      - error
